orcamentos/crm/urls.py
from django.urls import include, path
from orcamentos.crm import views as c

app_name = 'crm'

person_patterns = [
    path('', c.PersonList.as_view(), name='person_list'),
    path('add/', c.PersonCreate.as_view(), name='person_add'),
    path('<slug>/edit/', c.PersonUpdate.as_view(), name='person_edit'),
    path('<slug>/', c.person_detail, name='person_detail'),
]

customer_patterns = [
    path('', c.CustomerList.as_view(), name='customer_list'),
    path('add/', c.CustomerCreate.as_view(), name='customer_add'),
    path('<slug>/edit/', c.CustomerUpdate.as_view(), name='customer_edit'),
    path('<slug>/', c.customer_detail, name='customer_detail'),
]

employee_patterns = [
    path('add/', c.employee_create, name='employee_add'),
]

urlpatterns = [
    path('person/', include(person_patterns)),
    path('customer/', include(customer_patterns)),
    path('employee/', include(employee_patterns)),
]

orcamentos/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('orcamentos.core.urls', namespace='core')),
    path('crm/', include('orcamentos.crm.urls', namespace='crm')),
    path('proposal/', include('orcamentos.proposal.urls', namespace='proposal')),
    path('admin/', admin.site.urls),
]

orcamentos/crm/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from django.contrib.auth.models import User
from orcamentos.core.models import TimeStampedModel, Address
from .managers import CustomerManager, PersonManager, SellerManager
from orcamentos.utils.lists import GENDER, TREATMENT, PHONE_TYPE, PERSON_TYPE, CUSTOMER_TYPE


class People(TimeStampedModel, Address):
    gender = models.CharField(
        u'gênero',
        max_length=1,
        choices=GENDER,
        default='I',
        null=True,
        blank=True
    )
    treatment = models.CharField(
        'tratamento',
        max_length=4,
        choices=TREATMENT,
        null=True,
        blank=True
    )
    slug = models.SlugField('slug', blank=True)
    photo = models.URLField('foto', null=True, blank=True)
    company = models.CharField('empresa', max_length=50, null=True, blank=True)
    department = models.CharField('departamento', max_length=50, blank=True)
    cpf = models.CharField(
        'CPF',
        max_length=11,
        unique=True,
        null=True,
        blank=True
    )
    rg = models.CharField(
        'RG',
        max_length=11,
        null=True,
        blank=True
    )
    cnpj = models.CharField(
        'CNPJ',
        max_length=14,
        unique=True,
        null=True,
        blank=True
    )
    ie = models.CharField(
        u'inscrição estadual',
        max_length=12,
        null=True,
        blank=True
    )
    active = models.BooleanField('ativo', default=True)
    blocked = models.BooleanField('bloqueado', default=False)

    class Meta:
        abstract = True

    def __str__(self):
        return ' '.join(filter(None, [self.get_treatment_display(), self.first_name, self.last_name]))

    full_name = property(__str__)


class Person(People):
    first_name = models.CharField('nome', max_length=50)
    last_name = models.CharField(
        'sobrenome',
        max_length=50,
        null=True,
        blank=True
    )
    email = models.EmailField(null=True, blank=True)
    occupation = models.ForeignKey(
        'Occupation',
        verbose_name='cargo',
        related_name='person_occupation',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    person_type = models.CharField(
        'cliente ou contato',
        max_length=1,
        choices=PERSON_TYPE,
        default='p'
    )
    customer_type = models.CharField(
        'tipo de cliente',
        max_length=1,
        choices=CUSTOMER_TYPE,
        blank=True
    )

    objects = PersonManager()

    class Meta:
        ordering = ['first_name']
        verbose_name = 'contato'
        verbose_name_plural = 'contatos'

    def __str__(self):
        return self.full_name

    def get_absolute_url(self):
        return r('crm:person_detail', slug=self.slug)

    # def save(self):
    #     self.fullname = '{} {}'.format(self.first_name, self.last_name)
    #     self.slug = slugify(self.fullname)
    #     super(Person, self).save()


class PhonePerson(models.Model):
    phone = models.CharField('telefone', max_length=20, blank=True)
    person = models.ForeignKey('Person', on_delete=models.CASCADE)
    phone_type = models.CharField(
        'tipo',
        max_length=3,
        choices=PHONE_TYPE,
        default='pri'
    )


class Customer(Person):
    objects = CustomerManager()

    class Meta:
        proxy = True
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def get_absolute_url(self):
        return r('crm:customer_detail', slug=self.slug)


class Employee(People, User):
    occupation = models.ForeignKey(
        'Occupation',
        verbose_name='cargo',
        related_name='employee_occupation',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    internal = models.BooleanField('interno', default=True)
    commissioned = models.BooleanField('comissionado', default=True)
    commission = models.DecimalField(
        u'comissão',
        max_digits=6,
        decimal_places=2,
        default=0.01
    )
    date_release = models.DateTimeField(
        u'data de saída',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ['username']
        verbose_name = u'funcionário'
        verbose_name_plural = u'funcionários'


class PhoneEmployee(models.Model):
    phone = models.CharField('telefone', max_length=20, blank=True)
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)
    phone_type = models.CharField(
        'tipo',
        max_length=3,
        choices=PHONE_TYPE,
        default='pri'
    )


class Occupation(models.Model):
    occupation = models.CharField('cargo', max_length=50, unique=True)

    class Meta:
        ordering = ['occupation']
        verbose_name = 'cargo'
        verbose_name_plural = 'cargos'

    def __str__(self):
        return self.occupation


class Seller(Employee):
    objects = SellerManager()

    class Meta:
        proxy = True
        verbose_name = 'vendedor'
        verbose_name_plural = 'vendedores'


class ContactBase(models.Model):  # Active
    name = models.CharField('Nome', max_length=100, null=True, blank=True)
    email = models.EmailField('E-mail', null=True, blank=True)
    phone = models.CharField('Telefone', max_length=20, null=True, blank=True)
    phone_type = models.CharField(
        'tipo',
        max_length=3,
        choices=PHONE_TYPE,
        default='pri',
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class CompanyContact(ContactBase):
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Contato Cliente'
        verbose_name_plural = 'Contatos Clientes'

orcamentos/crm/forms.py
from django import forms
from orcamentos.utils.lists import GENDER, CUSTOMER_TYPE, PERSON_TYPE
from orcamentos.crm.models import Person, Employee, Customer


class SelectDateWidget(forms.SelectDateWidget):

    def create_select(self, *args, **kwargs):
        old_state = self.is_required
        self.is_required = False
        result = super().create_select(*args, **kwargs)
        self.is_required = old_state
        return result


class CustomerForm(forms.ModelForm):
    gender = forms.ChoiceField(
        label='Sexo', choices=GENDER, initial='M', widget=forms.RadioSelect)
    person_type = forms.ChoiceField(
        label='Cliente ou contato', choices=PERSON_TYPE, initial='c',
        widget=forms.RadioSelect)
    customer_type = forms.ChoiceField(
        label='Tipo', choices=CUSTOMER_TYPE, initial='p',
        widget=forms.RadioSelect)

    class Meta:
        model = Customer
        fields = (
            # 'active',
            'address',
            # 'blocked',
            # 'birthday',
            'cep',
            'city',
            'cnpj',
            'company',
            'complement',
            'cpf',
            'customer_type',
            'department',
            'district',
            'email',
            'first_name',
            'gender',
            'ie',
            'last_name',
            # 'occupation',
            'person_type',
            'photo',
            'rg',
            'slug',
            'treatment',
            'uf',
        )
        # widgets = {
        #     'birthday': SelectDateWidget
        # }

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     current_year = now().year
    #     self.fields['birthday'].widget.years = [
    #         current_year - x for x in range(50)][::-1]

    def clean_cpf(self):
        return self.cleaned_data['cpf'] or None

    def clean_cnpj(self):
        return self.cleaned_data['cnpj'] or None


class PersonForm(forms.ModelForm):
    gender = forms.ChoiceField(
        label='Sexo', choices=GENDER, initial='M', widget=forms.RadioSelect)
    person_type = forms.ChoiceField(
        label='Cliente ou contato', choices=PERSON_TYPE, initial='p',
        widget=forms.RadioSelect)

    class Meta:
        model = Person
        fields = (
            'gender', 'treatment', 'first_name', 'last_name', 'slug',
            'photo', 'occupation', 'company', 'department',
            'email', 'cpf', 'rg', 'cnpj', 'ie', 'person_type',
            'customer_type', 'address', 'complement', 'district',
            'city', 'uf', 'cep', 'active', 'blocked'
        )

    def clean_cpf(self):
        return self.cleaned_data['cpf'] or None

    def clean_cnpj(self):
        return self.cleaned_data['cnpj'] or None


class EmployeeForm(forms.ModelForm):
    password = forms.CharField(label='Senha', widget=forms.PasswordInput)

    class Meta:
        model = Employee
        fields = ['username', 'email', 'password']

    def clean_cpf(self):
        return self.cleaned_data['cpf'] or None

    def clean_cnpj(self):
        return self.cleaned_data['cnpj'] or None


class EmployeeAdminForm(forms.ModelForm):
    gender = forms.ChoiceField(
        label='Sexo', choices=GENDER, initial='M', widget=forms.RadioSelect)

    class Meta:
        model = Employee
        fields = (
            'username', 'slug', 'gender', 'first_name', 'last_name',
            'is_staff', 'email', 'photo', 'department',
            'cpf', 'rg', 'occupation', 'address', 'complement',
            'district', 'city', 'uf', 'cep', 'date_joined',
            'date_release', 'active', 'blocked'
        )

    def clean_cpf(self):
        return self.cleaned_data['cpf'] or None

    def clean_cnpj(self):
        return self.cleaned_data['cnpj'] or None

orcamentos/crm/views.py
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView
from django.views.generic.edit import UpdateView
from orcamentos.core.mixins import FirstnameSearchMixin
from orcamentos.utils.lists import CUSTOMER_TYPE
from .models import Person, Customer
from .forms import PersonForm, EmployeeForm, CustomerForm


class PersonList(LRM, FirstnameSearchMixin, ListView):
    model = Person
    paginate_by = 10


person_detail = DetailView.as_view(model=Person)


class PersonCreate(CreateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('crm:person_list')


class PersonUpdate(UpdateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('crm:person_list')


class CustomerList(FirstnameSearchMixin, ListView):
    model = Customer
    paginate_by = 10

    def get_queryset(self):
        queryset = super(CustomerList, self).get_queryset()
        filter_departments = self.request.GET.get('filter_departments')
        filter_customer_types = self.request.GET.get('filter_customer_types')

        if filter_departments:
            queryset = queryset.filter(Q(department=filter_departments))

        if filter_customer_types:
            queryset = queryset.filter(Q(customer_type=filter_customer_types))

        return queryset

    def get_context_data(self, **kwargs):
        context = super(CustomerList, self).get_context_data(**kwargs)

        departments = Customer.objects.exclude(department='')\
            .values_list('department', flat=True)
        context['departments'] = sorted(set(departments))

        context['customer_types'] = [
            {'value': item[0], 'text': item[1]}
            for item in CUSTOMER_TYPE
        ]

        filter_departments = self.request.GET.get('filter_departments')
        filter_customer_types = self.request.GET.get('filter_customer_types')

        # Devolve o valor selecionado pra manter o filtro aplicado no template.
        if filter_departments:
            context['selected_filter_department'] = filter_departments

        if filter_customer_types:
            context['selected_filter_customer_type'] = filter_customer_types

        return context

customer_detail = DetailView.as_view(model=Customer)


class CustomerCreate(CreateView):
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('crm:customer_list')


class CustomerUpdate(UpdateView):
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('crm:customer_list')


def employee_create(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            e = form.save(commit=False)
            e.slug = e.username
            e.is_staff = True
            e.set_password(form.cleaned_data['password'])
            e.save()
            return render(request, 'dashboard.html')
    else:
        form = EmployeeForm()
    return render(request, 'crm/employee_form.html', {'form': form})

orcamentos/crm/templates/crm/customer_detail.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}
  <title>Customer Detail</title>
{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="." method="get">
    <!-- edit -->
    <a href="{% url 'crm:customer_edit' customer.slug %}">
        <button id="edit_customer" type="button" class="btn btn-success">
            <span class="fa fa-pencil"></span> Editar
        </button>
    </a>
</form>

<div class="col-lg-8">
  <div class="col-md-2 column">
    <img src="{{ object.photo|default:'https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-person-128.png' }}" class="img-square" style="height: 100px;" />
  </div>
  <div class="col-md-offset-3 column">
    <h1>{{ object.full_name }}</h1>
    {% if object.email %}
      <h4><span class="glyphicon glyphicon-envelope"></span><a href="#"> {{ object.email }}</a></h4>
    {% endif %}
  </div>

  </br>

  <table class="table table-user-information">
    <tbody>
      {% if object.type_custom == 'p' %}
        <tr>
          <th class="col-md-3 text-right">Gênero</th>
          <td>{{ object.get_gender_display }}</td>
        </tr>
      {% endif %}
      {% if object.company %}
        <tr>
          <th class="col-md-3 text-right">Empresa</th>
          <td>{{ object.company }}</td>
        </tr>
      {% endif %}
      {% if object.department %}
        <tr>
          <th class="col-md-3 text-right">Departamento</th>
          <td>{{ object.department }}</td>
        </tr>
      {% endif %}
      {% if object.phone1 %}
        <tr>
          <th class="col-md-3 text-right">Telefone 1</th>
          <td>{{ object.phone1 }}</td>
        </tr>
      {% else %}
        <tr>
          <th class="col-md-3 text-right">Telefone 1</th>
          <td>---</td>
        </tr>
      {% endif %}
      {% if object.phone2 %}
        <tr>
          <th class="col-md-3 text-right">Telefone 2</th>
          <td>{{ object.phone2 }}</td>
        </tr>
      {% endif %}
      {% if object.phone3 %}
        <tr>
          <th class="col-md-3 text-right">Telefone 3</th>
          <td>{{ object.phone3 }}</td>
        </tr>
      {% endif %}
      {% if object.cpf %}
        <tr>
          <th class="col-md-3 text-right">CPF</th>
          <td>{{ object.cpf }}</td>
        </tr>
      {% endif %}
      {% if object.rg %}
        <tr>
          <th class="col-md-3 text-right">RG</th>
          <td>{{ object.rg }}</td>
        </tr>
      {% endif %}
      {% if object.cnpj %}
        <tr>
          <th class="col-md-3 text-right">CNPJ</th>
          <td>{{ object.cnpj }}</td>
        </tr>
      {% endif %}
      {% if object.ie %}
        <tr>
          <th class="col-md-3 text-right">IE</th>
          <td>{{ object.ie }}</td>
        </tr>
      {% endif %}
      <tr>
        <th class="col-md-3 text-right">Ativo</th>
          <td><span class="glyphicon {{ object.active|yesno:'glyphicon-ok-sign ok,glyphicon-minus-sign no'}}"></span></td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Bloqueado</th>
          <td><span class="glyphicon {{ object.blocked|yesno:'glyphicon-ok-sign ok,glyphicon-minus-sign no'}}"></span></td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Tipo de cliente</th>
        <td>{{ object.get_customer_type_display }}</td>
      </tr>

      {% if object.address %}
        <tr>
          <th class="col-md-3 text-right">Endereço</th>
          <td>{{ object.address }}</td>
        </tr>
      {% endif %}
      {% if object.complement %}
        <tr>
          <th class="col-md-3 text-right">Complemento</th>
          <td>{{ object.complement }}</td>
        </tr>
      {% endif %}
      {% if object.district %}
        <tr>
          <th class="col-md-3 text-right">Bairro</th>
          <td>{{ object.district }}</td>
        </tr>
      {% endif %}
      {% if object.city %}
        <tr>
          <th class="col-md-3 text-right">Cidade</th>
          <td>{{ object.city }}</td>
        </tr>
      {% endif %}
      {% if object.uf %}
        <tr>
          <th class="col-md-3 text-right">UF</th>
          <td>{{ object.uf }}</td>
        </tr>
      {% endif %}
      {% if object.cep %}
        <tr>
          <th class="col-md-3 text-right">CEP</th>
          <td>{{ object.cep }}</td>
        </tr>
      {% endif %}

    </tbody>
  </table>
</div>

{% endblock content %}

orcamentos/crm/templates/crm/customer_form.html
{% extends "base.html" %}

{% load bootstrap widget_tweaks %}

{% block title %}
	<title>Customer Form</title>
{% endblock title %}

{% block content %}

<style>
  .form-inline .form-group { margin-right:10px; }
  .well-primary {
  color: rgb(255, 255, 255);
  background-color: rgb(66, 139, 202);
  border-color: rgb(53, 126, 189);
  }
  .glyphicon { margin-right:5px; }
</style>

<form action="." method="POST">
    {% csrf_token %}
  <div class="row">
    <div class="col-md-12">
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="fa fa-user"></span> Cliente</a> </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.gender|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group invisible">
                    {{ form.person_type|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.customer_type|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.treatment|bootstrap }}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group required">
                    {{ form.first_name|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.last_name|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.email|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="form-group">
                      <label class="control-label">
                        {{ form.slug.label }} <a href="#" data-toggle="popover" title="Slug" data-content="É um texto em minúsculo e separado por traços. Ex: lorem-ipsum-amet."><i class="fa fa-question-circle azul-claro"></i></a>
                      </label>
                      <div class="">
                        {{ form.slug|attr:"class:form-control" }} {{ form.slug.errors }}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.company|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.department|bootstrap }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="fa fa-file-text-o"></span> Documentos</a> </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.photo|bootstrap }}
                  </div>
                </div>
                <!-- <div class="col-md-6">
                  <div class="form-group">
                    { form.birthday|bootstrap }}
                  </div>
                </div> -->
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.cpf|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.rg|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.cnpj|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.ie|bootstrap }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="fa fa-map-marker"></span> Endereço</a> </h4>
          </div>
          <div id="collapseThree" class="panel-collapse collapse">
            <div class="panel-body">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.address|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.complement|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.district|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.city|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.uf|bootstrap }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {{ form.cep|bootstrap }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>

	<div class="form-group">
      <div class="col-sm-10 col-sm-offset-2">
        <button type="submit" id="id_submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
</div>
</form>

<script>
  $(document).ready(function(){
    $('[data-toggle="popover"]').popover();

    $('#id_slug').slugify('#id_first_name');
  });
</script>
{% endblock content %}

orcamentos/crm/templates/crm/customer_list.html
{% extends "base.html" %}

{% block title %}
  <title>Clientes</title>
{% endblock title %}

{% block content %}

<form id="formFilter" class="navbar-form navbar-right" action="." method="GET">
  <!-- add -->
  <a href="{% url 'crm:customer_add' %}">
    <button id="new_customer" type="button" class="btn btn-primary">
      <span class="glyphicon glyphicon-plus"></span> Adicionar
    </button>
  </a>
  <!-- search form -->
  <div class="form-group">
    <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
    <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
    <a href="." class="btn btn-link">Limpar</a>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <h6>Filtrar por Departamento</h6>

      <select id="filterDepartments" name="filter_departments" class="form-control">
        <option value="">Todos</option>
        {% for department in departments %}
          {% if department == selected_filter_department %}
            <option value="{{ department }}" selected>{{ department }}</option>
          {% else %}
            <option value="{{ department }}">{{ department }}</option>
          {% endif %}
        {% endfor %}
      </select>

    </div>

    <div class="col-sm-6">
      <h6>Filtrar por Tipo de Cliente</h6>

      <select id="filterCustomerTypes" name="filter_customer_types" class="form-control">
        <option value="">Todos</option>
        {% for customer_type in customer_types %}
          {% if customer_type.value == selected_filter_customer_type %}
            <option value="{{ customer_type.value }}" selected>{{ customer_type.text }}</option>
          {% else %}
            <option value="{{ customer_type.value }}">{{ customer_type.text }}</option>
          {% endif %}
        {% endfor %}
      </select>

    </div>

  </div>
</form>

<div class="page-header" style="margin-top: 80px;">
<h2><i class="fa fa-users"></i> Lista de Clientes</h2>
</div>

{% if customer_list %}
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Foto</th>
      <th>e-mail</th>
      <th>Telefone</th>
      <th>Empresa</th>
      <th>Departamento</th>
      <th>Tipo de cliente</th>
    </tr>
  </thead>
  <tbody>
  {% for customer in customer_list %}
    <tr>
      <td><a href="{{ customer.get_absolute_url }}">{{ customer.full_name }}</a></td>
      <td><img src="{{ customer.photo|default:'https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-person-128.png' }}" class="img-square" style="height: 20px;" /></td>
      <td>{{ customer.email|default:"---" }}</td>
      <td>{{ customer.phone1|default:"---" }}</td>
      <td>{{ customer.company|default:"---" }}</td>
      <td>{{ customer.department|default:"---" }}</td>
      <td><i class="fa fa-circle fa-fw {{ customer.get_customer_type_display }}"></i> {{ customer.get_customer_type_display }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}

<hr>
<div>
<h3>{{ customer_list|length }} cliente{{ customer_list|length|pluralize }}</h3>
<h4><b>Total:</b> {{ page_obj.paginator.count }} cliente{{ page_obj.paginator.count|pluralize }}</h4>
</div>

<!-- pagination -->
{% include "pagination.html" %}

<script>

  $('#filterDepartments').on('change', function() {
    $('#formFilter').submit();
  });

  $('#filterCustomerTypes').on('change', function() {
    $('#formFilter').submit();
  });

</script>

{% endblock content %}

orcamentos/crm/templates/crm/person_list.html
{% extends 'base.html' %}

{% block title %}
  <title>Contatos</title>
{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="." method="get">
    <!-- add -->
    <a href="{% url 'crm:person_add' %}">
        <button id="new_customer" type="button" class="btn btn-primary">
            <span class="glyphicon glyphicon-plus"></span> Adicionar
        </button>
    </a>
    <!-- search form -->
    <div class="form-group">
      <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
      <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
  </div>
</form>

<div class="page-header">
<h2><h2><i class="fa fa-user"></i> Lista de Contatos</h2>
</div>

<div>
{% if person_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Foto</th>
        <th>Email</th>
        <th>Empresa</th>
      </tr>
    </thead>
    <tbody>
    {% for person in person_list %}
      <tr>
        <td><a href="{{ person.get_absolute_url }}">{{ person.full_name }}</a></td>
        <td><img src="{{ person.photo|default:'https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-person-128.png' }}" class="img-square" style="height: 20px;" /></td>
        <td>{{ person.email }}</td>
        <td>{{ person.company }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}
</div>

<hr>
<div>
<h3>{{ person_list|length }} contato{{ person_list|length|pluralize }}</h3>
<h4><b>Total:</b> {{ page_obj.paginator.count }} contato{{ page_obj.paginator.count|pluralize }}</h4>
</div>

<!-- pagination -->
{% include "pagination.html" %}

{% endblock content %}