orcamentos/core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from orcamentos.core.views import home, welcome, Dashboard, status

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    # path('inscricao/', subscription, name='subscription'),
    path('bemvindo/', welcome, name='welcome'),
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('status/', status, name='status'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

orcamentos/crm/urls.py
from django.urls import include, path
from orcamentos.crm import views as c

app_name = 'crm'

person_patterns = [
    path('', c.PersonList.as_view(), name='person_list'),
    path('add/', c.PersonCreate.as_view(), name='person_add'),
    path('<slug>/edit/', c.PersonUpdate.as_view(), name='person_edit'),
    path('<slug>/', c.person_detail, name='person_detail'),
]

customer_patterns = [
    path('', c.CustomerList.as_view(), name='customer_list'),
    path('add/', c.CustomerCreate.as_view(), name='customer_add'),
    path('<slug>/edit/', c.CustomerUpdate.as_view(), name='customer_edit'),
    path('<slug>/', c.customer_detail, name='customer_detail'),
]

employee_patterns = [
    path('add/', c.employee_create, name='employee_add'),
]

urlpatterns = [
    path('person/', include(person_patterns)),
    path('customer/', include(customer_patterns)),
    path('employee/', include(employee_patterns)),
]

orcamentos/proposal/urls.py
from django.urls import include, path
from orcamentos.proposal import views as p
from orcamentos.proposal import actions as a
from orcamentos.proposal import graphics as g

app_name = 'proposal'

entry_patterns = [
    path('', p.EntryList.as_view(), name='entry_list'),
    path('<int:pk>/', p.entry_detail, name='entry_detail'),
    path('<int:pk>/json/', p.entry_detail_json, name='entry_detail_json'),
    path('<int:pk>/edit/', p.entry_update, name='entry_edit'),
    path('add/', p.entry_create, name='entry_add'),

    # Create Proposal
    path('<int:entry_id>/proposal/new/',
         a.create_proposal,
         name='create_proposal_url'),
]

proposal_patterns = [
    path('', p.ProposalList.as_view(), name='proposal_list'),
    path('<int:pk>/', p.ProposalDetail.as_view(), name='proposal_detail'),
    path('<int:pk>/edit/', p.ProposalUpdate.as_view(), name='proposal_edit'),

    # # Conclude Proposal
    path('<int:proposal_id>/ok/',
         a.conclude_proposal,
         name='conclude_proposal'),
    # Cancel Proposal
    path('<int:proposal_id>/cancel/',
         a.cancel_proposal,
         name='cancel_proposal'),
    # Create Contract
    path('<int:proposal_id>/contract/new/',
         a.create_contract,
         name='create_contract_url'),
    # Create Option
    path(
        '<int:proposal_id>/proposal/create_option/',
        a.create_option,
        name='create_option_url'
    ),
    path('proposal_per_status_json/', g.proposal_per_status_json),
    path('contract_aprov_canceled_json/', g.contract_aprov_canceled_json),
    path('contract_more_expensive_json/', g.contract_more_expensive_json),
    path('contract_total_per_month_json/', g.contract_total_per_month_json),
    path('percent_type_customer_json/', g.percent_type_customer_json),
]

contract_patterns = [
    path('', p.ContractList.as_view(), name='contract_list'),
    path('<int:pk>/', p.contract_detail, name='contract_detail'),
    path('<int:pk>/edit/', p.ContractUpdate.as_view(), name='contract_edit'),
]

work_patterns = [
    path('', p.WorkList.as_view(), name='work_list'),
    path('add/', p.work_create, name='work_add'),
    path('<slug>/edit/', p.work_update, name='work_edit'),
    path('<slug>/', p.work_detail, name='work_detail'),
]


urlpatterns = [
    path('entry/', include(entry_patterns)),
    path('proposal/', include(proposal_patterns)),
    path('contract/', include(contract_patterns)),
    path('work/', include(work_patterns)),
]

orcamentos/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('orcamentos.core.urls', namespace='core')),
    path('crm/', include('orcamentos.crm.urls', namespace='crm')),
    path('proposal/', include('orcamentos.proposal.urls', namespace='proposal')),
    path('admin/', admin.site.urls),
]

orcamentos/core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(u'endereço', max_length=100, blank=True)
    complement = models.CharField('complemento', max_length=100, blank=True)
    district = models.CharField('bairro', max_length=100, blank=True)
    city = models.CharField('cidade', max_length=100, blank=True)
    uf = models.CharField(
        'UF', max_length=2,
        choices=STATE_CHOICES,
        blank=True
    )
    cep = models.CharField('CEP', max_length=9, blank=True)

    class Meta:
        abstract = True

orcamentos/core/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.db.models import IntegerField, Count, Case, When
from orcamentos.proposal.models import Proposal
from orcamentos.crm.forms import EmployeeForm
from .mixins import DashboardMixin


def home(request):
    if request.user.is_authenticated:
        return redirect('core:dashboard')
    return render(request, 'index.html')


def welcome(request):
    return render(request, 'welcome.html')


def subscription(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            e = form.save(commit=False)
            e.slug = e.username
            e.is_staff = True
            e.set_password(form.cleaned_data['password'])
            e.save()
            return redirect('core:welcome')
    else:
        form = EmployeeForm()
    return render(request, 'subscription.html', {'form': form})


class Dashboard(DashboardMixin, TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        p = Proposal.objects.aggregate(
            proposals=Count('pk'),
            proposal_elab=Count(
                Case(When(status='elab', then=1), output_field=IntegerField())),
            proposal_pending=Count(
                Case(When(status='p', then=1), output_field=IntegerField())),
            proposal_concluded=Count(
                Case(When(status='co', then=1), output_field=IntegerField())),
            proposal_approved=Count(
                Case(When(status='a', then=1), output_field=IntegerField())),
            proposal_canceled=Count(
                Case(When(status='c', then=1), output_field=IntegerField())),
        )
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['proposals'] = p
        context['proposal_list'] = self.proposal_list()
        context['proposal_elab'] = self.proposal_elab()
        context['entrys'] = self.entry_list()
        context['contract_total_per_month'] = self.contract_total_per_month()
        context['contract_total_per_year'] = self.contract_total_per_year()

        return context


def status(request):
    return render(request, 'status.html')

orcamentos/core/templates/about.html
{% extends 'base.html' %}

{% block content %}

	<div class="container lead">
		<p>Este é um sistema para controle de orçamentos. E cadastro de clientes.</p>
	</div>
{% endblock %}

orcamentos/core/templates/base.html
{% extends "base_initial.html" %}

{% block style %}
    <style type="text/css">
    body {
      padding-top: 50px;
    }
    .errorlist {
        color: #e74c3c;
    }
  </style>
{% endblock style %}

{% block menu %}
  {% include "menu.html" %}
{% endblock menu %}

orcamentos/core/templates/base_initial.html
<!DOCTYPE html>
<html>
<head>

  {% load static from staticfiles %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
  <link rel="shortcut icon" href="{% static "img/favicon-list.ico" %}">
  <link rel="stylesheet" href="{% static "css/bootstrap.css.map" %}">
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/morris.css" %}">
  <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.min.css" %}">
  <!-- <link rel="stylesheet" href="{% static "css/style.css" %}"> -->
  <link rel="stylesheet" href="{% static "css/stylenew.css" %}">
  <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
  <link rel="stylesheet" href="{% static "css/status.css" %}">
  <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.min.css" %}">

  <!-- Add IntroJs styles -->
  <link rel="stylesheet" href="{% static "css/introjs.css" %}">

  <!-- MetisMenu CSS -->
  <link href="{% static "css/metisMenu.min.css" %}" rel="stylesheet">

  <!-- Timeline CSS -->
  <link href="{% static "css/timeline.css" %}" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="{% static "css/sb-admin-2.css" %}" rel="stylesheet">

  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/transition.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/bootstrap-datepicker.min.js" %}"></script>
  <script src="{% static "js/bootstrap-datepicker.pt-BR.min.js" %}"></script>
  <script src="{% static "js/raphael-min.js" %}"></script>
  <script src="{% static "js/metisMenu.min.js" %}"></script>
  <script src="{% static "js/jquery.slugify.js" %}"></script>
  <script src="{% static "js/intro.js" %}"></script>

  {% block title %}
    <title>Orçamentos</title>
  {% endblock title %}

{% block style %}{% endblock style %}
  
</head>

<body>

{% block menu %}{% endblock menu %}

{% block nocontent %}
  
{% endblock nocontent %}

<div class="container">
  {% block content %}

  {% endblock content %}
</div>

{% block footer %}{% endblock footer %}

  {% block js %}
    
  {% endblock js %}

</body>
</html>

orcamentos/core/templates/contact.html
{% extends "base.html" %}

{% block tittle %}
    <title>Contato</title>
{% endblock tittle %}

{% block content %}
    <h1>Contato</h1>
{% endblock content %}

orcamentos/core/templates/footer.html
<!-- Footer -->
<footer class="navbar-inverse letter-white">
    <div class="container">
        <div class="row clearfix">
            <div class="text-center">
                <p class="pull-right">
                    <a href="#">Topo</a>
                </p>
                <p>rg solutions &copy; 2015 &middot; all righs reserved <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/" target="_blank"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/br/80x15.png" /></a> </p><!-- background image -->
            </div>
        </div>
    </div>        
</footer>

orcamentos/core/templates/index.html
{% extends "base_initial.html" %}

{% load static from staticfiles %}

{% block style %}
  <!-- Custom CSS -->
  <link href="{% static "css/rgscale.css" %}" rel="stylesheet">
{% endblock style %}

{% block nocontent %}

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div>
                        <h3>Bem vindo ao controle de orçamentos!</h3>
                        <p>Com ele você pode gerenciar seus clientes e obras e acompanhar o status dos seus orçamentos.</p>
                        <a href="{% url 'core:dashboard' %}">
                            <button class="btn btn-lg btn-dark-blue">Faça um teste gratuito</button>
                        </a>
                        <p><small>Usuário: admin - Senha: admin</small></p>
                    </div>
                </div>
            </div>
        </div>
    </header>


{% endblock nocontent %}

orcamentos/core/templates/menu.html
<!-- Menu -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url 'core:dashboard' %}"><span class="fa fa-sellsy"></span> Dashboard</a></li>
        <li><a href="{% url 'proposal:entry_list' %}"><span class="fa fa-inbox"></span> Entrada</a></li>
        <!-- <li><a href="#"><span class="fa fa-magic fa-flip-horizontal"></span> Cadastro rápido</a></li> -->
        <li><a href="{% url 'proposal:proposal_list' %}"><span class="fa fa-list"></span> Orçamentos</a></li>
        <li><a href="{% url 'proposal:contract_list' %}"><span class="fa fa-star"></span> Contratos</a></li>
        <li><a href="{% url 'crm:customer_list' %}"><span class="fa fa-users"></span> Clientes</a></li>
        <li><a href="{% url 'proposal:work_list' %}"><span class="fa fa-home"></span> Obras</a></li>
        <li><a href="{% url 'crm:person_list' %}"><span class="fa fa-user"></span> Contatos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}"><span class="fa fa-drupal"></span> Admin</a></li>
      </ul>
    </div>
  </div>
</div>

orcamentos/core/templates/pagination.html
<!-- pagination -->
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}&search_box={{ request.GET.search_box }}&filter_departments={{ request.GET.filter_departments }}&filter_customer_types={{ request.GET.filter_customer_types }}">&laquo;</a></li>
      {% endif %}

      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 3 primeiras e 3 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == 3 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' or pg == page_obj.paginator.num_pages|add:'-2' %}
          <li><a href="?page={{ pg }}&search_box={{ request.GET.search_box }}&filter_departments={{ request.GET.filter_departments }}&filter_customer_types={{ request.GET.filter_customer_types }}">{{ pg }}</a></li>
        {% else %}
          {% if page_obj.number == pg %}
            <li class="active"><a href="?page={{ pg }}&search_box={{ request.GET.search_box }}&filter_departments={{ request.GET.filter_departments }}&filter_customer_types={{ request.GET.filter_customer_types }}">{{ pg }}</a></li>
          {% elif pg > page_obj.number|add:'-4' and pg < page_obj.number|add:'4' %}
            <!-- Mostra 3 páginas antes e 3 páginas depois da atual -->
            <li><a href="?page={{ pg }}&search_box={{ request.GET.search_box }}&filter_departments={{ request.GET.filter_departments }}&filter_customer_types={{ request.GET.filter_customer_types }}">{{ pg }}</a></li>
          {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
            <li><a href="">...</a></li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}&search_box={{ request.GET.search_box }}&filter_departments={{ request.GET.filter_departments }}&filter_customer_types={{ request.GET.filter_customer_types }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>

<!-- https://gist.github.com/rg3915/01ca76f099f431c24bc0536bef83076b -->

<!-- https://www.technovelty.org/web/skipping-pages-with-djangocorepaginator.html -->

orcamentos/core/templates/status.html
{% extends "base.html" %}

{% block content %}
	<br>
	<div class="col-lg-2">
		<a href="#" class="btn btn-block btn-red">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-orange">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-yellow">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-light-green">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-green">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-dark-green">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-light-blue">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-blue">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-dark-blue">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-violet">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-brown">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-gray">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-dark-gray">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-black">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
		<a href="#" class="btn btn-block btn-transparent">
			<span class="fa fa-lg fa-fw fa-question"></span>
		</a>
	</div>
{% endblock content %}

orcamentos/core/templates/subscription.html
{% extends "base_initial.html" %}

{% load widget_tweaks %}

{% block title %}
  <title>Registration</title>
{% endblock title %}

{% block content %}

<div class="page-header">
  <h2>Vamos começar?</h2>
</div>

<form class="form-horizontal" action="." method="POST">
  {% csrf_token %}
  <ul class="errorlist nonfield"></ul>
  {{ form.non_fields_errors }}
  <div class="form-group required">
    <label class="control-label col-sm-2 col-lg-2">
      {{ form.username.label }}
    </label>
    <div class="col-sm-4 col-lg-4">
      {{ form.username|attr:"class:form-control" }} {{ form.username.errors }}
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2 col-lg-2">
      {{ form.email.label }}
    </label>
    <div class="col-sm-4 col-lg-4">
      {{ form.email|attr:"class:form-control" }} {{ form.email.errors }}
    </div>
  </div>
  <div class="form-group required">
    <label class="control-label col-sm-2 col-lg-2">
      {{ form.password.label }}
    </label>
    <div class="col-sm-4 col-lg-4 controls">
      {{ form.password|attr:"class:form-control" }} {{ form.password.errors }}
    </div>
  </div>

  <div class="form-group">
      <div class="col-sm-4 col-sm-offset-2">
        <p><b>Atenção:</b> Você não receberá nenhum e-mail.</p>
        <button type="submit" class="btn btn-primary">Cadastrar-se</button></br>
        <a href="{% url 'core:dashboard' %}">Já tenho cadastro</a>
      </div>
    </div>
</form>

{% endblock content %}

orcamentos/core/templates/welcome.html
{% extends "base_initial.html" %}

{% load static from staticfiles %}

{% block style %}
  <!-- Custom CSS -->
  <link href="{% static "css/rgscale.css" %}" rel="stylesheet">
{% endblock style %}

{% block nocontent %}

  <!-- Intro Header -->
  <header class="intro">
      <div class="intro-body">
          <div class="container">
              <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                      <h3>Bem vindo ao controle de orçamentos!</h3>
                      <a href="{% url 'core:dashboard' %}" class="page-scroll">
                          <button class="btn btn-lg btn-dark-blue">Próximo</button>
                      </a>
                  </div>
              </div>
          </div>
      </div>
  </header>

{% endblock nocontent %}