orcamentos/proposal/urls.py
from django.urls import include, path
from orcamentos.proposal import views as p
from orcamentos.proposal import actions as a
from orcamentos.proposal import graphics as g

app_name = 'proposal'

entry_patterns = [
    path('', p.EntryList.as_view(), name='entry_list'),
    path('<int:pk>/', p.entry_detail, name='entry_detail'),
    path('<int:pk>/json/', p.entry_detail_json, name='entry_detail_json'),
    path('<int:pk>/edit/', p.entry_update, name='entry_edit'),
    path('add/', p.entry_create, name='entry_add'),

    # Create Proposal
    path('<int:entry_id>/proposal/new/',
         a.create_proposal,
         name='create_proposal_url'),
]

proposal_patterns = [
    path('', p.ProposalList.as_view(), name='proposal_list'),
    path('<int:pk>/', p.ProposalDetail.as_view(), name='proposal_detail'),
    path('<int:pk>/edit/', p.ProposalUpdate.as_view(), name='proposal_edit'),

    # # Conclude Proposal
    path('<int:proposal_id>/ok/',
         a.conclude_proposal,
         name='conclude_proposal'),
    # Cancel Proposal
    path('<int:proposal_id>/cancel/',
         a.cancel_proposal,
         name='cancel_proposal'),
    # Create Contract
    path('<int:proposal_id>/contract/new/',
         a.create_contract,
         name='create_contract_url'),
    # Create Option
    path(
        '<int:proposal_id>/proposal/create_option/',
        a.create_option,
        name='create_option_url'
    ),
    path('proposal_per_status_json/', g.proposal_per_status_json),
    path('contract_aprov_canceled_json/', g.contract_aprov_canceled_json),
    path('contract_more_expensive_json/', g.contract_more_expensive_json),
    path('contract_total_per_month_json/', g.contract_total_per_month_json),
    path('percent_type_customer_json/', g.percent_type_customer_json),
]

contract_patterns = [
    path('', p.ContractList.as_view(), name='contract_list'),
    path('<int:pk>/', p.contract_detail, name='contract_detail'),
    path('<int:pk>/edit/', p.ContractUpdate.as_view(), name='contract_edit'),
]

work_patterns = [
    path('', p.WorkList.as_view(), name='work_list'),
    path('add/', p.work_create, name='work_add'),
    path('<slug>/edit/', p.work_update, name='work_edit'),
    path('<slug>/', p.work_detail, name='work_detail'),
]


urlpatterns = [
    path('entry/', include(entry_patterns)),
    path('proposal/', include(proposal_patterns)),
    path('contract/', include(contract_patterns)),
    path('work/', include(work_patterns)),
]

orcamentos/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('orcamentos.core.urls', namespace='core')),
    path('crm/', include('orcamentos.crm.urls', namespace='crm')),
    path('proposal/', include('orcamentos.proposal.urls', namespace='proposal')),
    path('admin/', admin.site.urls),
]

orcamentos/crm/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from django.contrib.auth.models import User
from orcamentos.core.models import TimeStampedModel, Address
from .managers import CustomerManager, PersonManager, SellerManager
from orcamentos.utils.lists import GENDER, TREATMENT, PHONE_TYPE, PERSON_TYPE, CUSTOMER_TYPE


class People(TimeStampedModel, Address):
    gender = models.CharField(
        u'gênero',
        max_length=1,
        choices=GENDER,
        default='I',
        null=True,
        blank=True
    )
    treatment = models.CharField(
        'tratamento',
        max_length=4,
        choices=TREATMENT,
        null=True,
        blank=True
    )
    slug = models.SlugField('slug', blank=True)
    photo = models.URLField('foto', null=True, blank=True)
    company = models.CharField('empresa', max_length=50, null=True, blank=True)
    department = models.CharField('departamento', max_length=50, blank=True)
    cpf = models.CharField(
        'CPF',
        max_length=11,
        unique=True,
        null=True,
        blank=True
    )
    rg = models.CharField(
        'RG',
        max_length=11,
        null=True,
        blank=True
    )
    cnpj = models.CharField(
        'CNPJ',
        max_length=14,
        unique=True,
        null=True,
        blank=True
    )
    ie = models.CharField(
        u'inscrição estadual',
        max_length=12,
        null=True,
        blank=True
    )
    active = models.BooleanField('ativo', default=True)
    blocked = models.BooleanField('bloqueado', default=False)

    class Meta:
        abstract = True

    def __str__(self):
        return ' '.join(filter(None, [self.get_treatment_display(), self.first_name, self.last_name]))

    full_name = property(__str__)


class Person(People):
    first_name = models.CharField('nome', max_length=50)
    last_name = models.CharField(
        'sobrenome',
        max_length=50,
        null=True,
        blank=True
    )
    email = models.EmailField(null=True, blank=True)
    occupation = models.ForeignKey(
        'Occupation',
        verbose_name='cargo',
        related_name='person_occupation',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    person_type = models.CharField(
        'cliente ou contato',
        max_length=1,
        choices=PERSON_TYPE,
        default='p'
    )
    customer_type = models.CharField(
        'tipo de cliente',
        max_length=1,
        choices=CUSTOMER_TYPE,
        blank=True
    )

    objects = PersonManager()

    class Meta:
        ordering = ['first_name']
        verbose_name = 'contato'
        verbose_name_plural = 'contatos'

    def __str__(self):
        return self.full_name

    def get_absolute_url(self):
        return r('crm:person_detail', slug=self.slug)

    # def save(self):
    #     self.fullname = '{} {}'.format(self.first_name, self.last_name)
    #     self.slug = slugify(self.fullname)
    #     super(Person, self).save()


class PhonePerson(models.Model):
    phone = models.CharField('telefone', max_length=20, blank=True)
    person = models.ForeignKey('Person', on_delete=models.CASCADE)
    phone_type = models.CharField(
        'tipo',
        max_length=3,
        choices=PHONE_TYPE,
        default='pri'
    )


class Customer(Person):
    objects = CustomerManager()

    class Meta:
        proxy = True
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def get_absolute_url(self):
        return r('crm:customer_detail', slug=self.slug)


class Employee(People, User):
    occupation = models.ForeignKey(
        'Occupation',
        verbose_name='cargo',
        related_name='employee_occupation',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    internal = models.BooleanField('interno', default=True)
    commissioned = models.BooleanField('comissionado', default=True)
    commission = models.DecimalField(
        u'comissão',
        max_digits=6,
        decimal_places=2,
        default=0.01
    )
    date_release = models.DateTimeField(
        u'data de saída',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ['username']
        verbose_name = u'funcionário'
        verbose_name_plural = u'funcionários'


class PhoneEmployee(models.Model):
    phone = models.CharField('telefone', max_length=20, blank=True)
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)
    phone_type = models.CharField(
        'tipo',
        max_length=3,
        choices=PHONE_TYPE,
        default='pri'
    )


class Occupation(models.Model):
    occupation = models.CharField('cargo', max_length=50, unique=True)

    class Meta:
        ordering = ['occupation']
        verbose_name = 'cargo'
        verbose_name_plural = 'cargos'

    def __str__(self):
        return self.occupation


class Seller(Employee):
    objects = SellerManager()

    class Meta:
        proxy = True
        verbose_name = 'vendedor'
        verbose_name_plural = 'vendedores'


class ContactBase(models.Model):  # Active
    name = models.CharField('Nome', max_length=100, null=True, blank=True)
    email = models.EmailField('E-mail', null=True, blank=True)
    phone = models.CharField('Telefone', max_length=20, null=True, blank=True)
    phone_type = models.CharField(
        'tipo',
        max_length=3,
        choices=PHONE_TYPE,
        default='pri',
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class CompanyContact(ContactBase):
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Contato Cliente'
        verbose_name_plural = 'Contatos Clientes'

orcamentos/proposal/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from django.utils.text import slugify
from django.utils.formats import number_format
from orcamentos.core.models import TimeStampedModel, Address
from .managers import EntryManager, ProposalManager
from orcamentos.utils.lists import PRIORITY, NORMAL, CATEGORY, PROP_TYPE, STATUS_LIST


class Work(Address):
    name_work = models.CharField('obra', max_length=100, unique=True)
    slug = models.SlugField('slug', blank=True)
    person = models.ForeignKey(
        'crm.Person',
        verbose_name='contato',
        related_name='work_person',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    customer = models.ForeignKey(
        'crm.Customer',
        verbose_name='cliente',
        related_name='work_customer',
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ['name_work']
        verbose_name = 'obra'
        verbose_name_plural = 'obras'

    def __str__(self):
        return self.name_work

    def get_absolute_url(self):
        if self.slug:
            return r('proposal:work_detail', slug=self.slug)

    def save(self):
        self.slug = slugify(self.name_work)
        super(Work, self).save()


class Proposal(TimeStampedModel):
    ''' Orçamento é todo orçamento com num_prop > 0 '''
    num_prop = models.PositiveIntegerField(u'número', default=0)
    priority = models.CharField(
        'prioridade',
        max_length=2,
        choices=PRIORITY,
        default=NORMAL
    )
    prop_type = models.CharField(
        u'tipo de orçamento',
        max_length=20,
        choices=PROP_TYPE,
        default='R'
    )
    num_prop_type = models.PositiveIntegerField(
        u'número da revisão',
        default=0
    )
    option_prop = models.PositiveIntegerField(
        'opção',
        null=True,
        blank=True,
        help_text='Cada orçamento pode ter opções 1, 2, 3 ...'
    )
    category = models.CharField(
        'categoria',
        max_length=4,
        choices=CATEGORY,
        default='orc'
    )
    description = models.TextField(u'descrição', blank=True)
    work = models.ForeignKey(
        'Work',
        verbose_name='obra',
        related_name='proposal_work',
        on_delete=models.CASCADE
    )
    person = models.ForeignKey(
        'crm.Person',
        verbose_name='contato',
        related_name='proposal_person',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    employee = models.ForeignKey(
        'crm.Employee',
        verbose_name=u'orçamentista',
        related_name='proposal_employee',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    seller = models.ForeignKey(
        'crm.Seller',
        verbose_name='vendedor',
        related_name='proposal_seller',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=4,
        choices=STATUS_LIST,
        default='elab'
    )
    date_conclusion = models.DateTimeField(
        u'data de conclusão',
        null=True,
        blank=True
    )
    price = models.DecimalField(
        'valor',
        max_digits=9,
        decimal_places=2,
        default=0
    )
    obs = models.TextField(u'observação', blank=True)
    created_orc = models.DateTimeField('orç. criado em', null=True, blank=True)

    objects = ProposalManager()

    class Meta:
        ordering = ['id']
        verbose_name = u'orçamento'
        verbose_name_plural = u'orçamentos'

    def __str__(self):
        # formato 001.15.0
        self.actual_year = self.created.strftime('%y')
        if self.option_prop:
            return f'{str(self.num_prop).zfill(3)}/{self.actual_year}{self.num_prop_type}-OP {self.option_prop}'
        return f'{str(self.num_prop).zfill(3)}/{self.actual_year}{self.num_prop_type}'
    codigo = property(__str__)

    def get_absolute_url(self):
        return r('proposal:proposal_detail', pk=self.pk)

    def get_price(self):
        return u"R$ %s" % number_format(self.price, 2)

    def get_customer(self):
        return self.work.customer
    cliente = property(get_customer)

    def get_customer_url(self):
        return u'/crm/customer/%s' % self.work.customer.slug

    def get_work_url(self):
        return u'/proposal/work/%s' % self.work.slug

    def get_person_url(self):
        return u'/crm/person/%s' % self.person.slug

    def get_seller(self):
        if self.seller:
            return '{} {}'.format(
                self.seller.employee.first_name,
                self.seller.employee.last_name
            )
        return ''

    def get_employee(self):
        if self.employee:
            return '{} {}'.format(self.employee.first_name, self.employee.last_name)
        return ''

    def get_address(self):
        if self.work.address:
            return '{}, {}, {} - {}'.format(
                self.work.address, self.work.district,
                self.work.city, self.work.uf
            )


class Entry(Proposal):
    ''' Entrada é todo orçamento com num_prop = 0 '''
    objects = EntryManager()

    class Meta:
        proxy = True
        ordering = ['priority', 'created']
        verbose_name = 'entrada'
        verbose_name_plural = 'entradas'

    def __str__(self):
        return str(self.work)

    def get_absolute_url(self):
        return r('proposal:entry_detail', pk=self.pk)

    def save(self):
        self.status = 'n'  # não iniciado
        super(Entry, self).save()


class Contract(TimeStampedModel):
    proposal = models.OneToOneField(
        'Proposal',
        verbose_name=u'orçamento',
        related_name='contract_proposal',
        on_delete=models.CASCADE
    )
    contractor = models.ForeignKey(
        'crm.Customer',
        verbose_name=u'contratante',
        related_name='contract_person',
        on_delete=models.CASCADE
    )
    is_canceled = models.BooleanField('cancelado', default=False)

    class Meta:
        ordering = ['proposal']
        verbose_name = u'contrato'
        verbose_name_plural = u'contratos'

    def __str__(self):
        return str(self.proposal)

    def get_absolute_url(self):
        return r('proposal:contract_detail', pk=self.pk)

    def get_price(self):
        return u"R$ %s" % number_format(self.proposal.price, 2)


class NumLastProposal(models.Model):
    num_last_prop = models.PositiveIntegerField(u'número', default=0)

    class Meta:
        verbose_name = u'número último orçamento'
        verbose_name_plural = u'número último orçamento'

    def __str__(self):
        return str(self.num_last_prop)

orcamentos/proposal/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView
from django.views.generic.edit import UpdateView
from .models import Entry, Proposal, Contract, Work
from .mixins import EntryMixin, ProposalMixin, ProposalDetailMixin, \
    ContractMixin, WorkMixin
from .forms import EntryForm, ProposalForm, ContractForm, WorkForm


class EntryList(EntryMixin, ListView):
    model = Entry
    paginate_by = 10


def entry_detail_json(request, pk):
    data = Entry.objects.filter(pk=pk)
    s = serializers.serialize("json", data)
    return HttpResponse(s)

entry_detail = DetailView.as_view(model=Entry)

entry_create = CreateView.as_view(
    model=Entry,
    form_class=EntryForm,
    success_url=reverse_lazy('proposal:entry_list')
)

entry_update = UpdateView.as_view(
    model=Entry,
    form_class=EntryForm,
    success_url=reverse_lazy('proposal:entry_list')
)


class ProposalList(ProposalMixin, ListView):
    model = Proposal
    paginate_by = 10


class ProposalDetail(ProposalDetailMixin, DetailView):
    model = Proposal


class ProposalUpdate(UpdateView):
    model = Proposal
    form_class = ProposalForm


class ContractList(ContractMixin, ListView):
    model = Contract
    paginate_by = 10


contract_detail = DetailView.as_view(model=Contract)


class ContractUpdate(UpdateView):
    model = Contract
    form_class = ContractForm


class WorkList(WorkMixin, ListView):
    model = Work
    paginate_by = 10


work_detail = DetailView.as_view(model=Work)

work_create = CreateView.as_view(
    model=Work,
    form_class=WorkForm,
    success_url=reverse_lazy('proposal:work_list')
)

work_update = UpdateView.as_view(
    model=Work,
    form_class=WorkForm,
    success_url=reverse_lazy('proposal:work_list')
)

orcamentos/proposal/templates/proposal/entry_detail.html
{% extends "base.html" %}

{% block title %}
	<title>Entry Detail</title>
{% endblock title %}

{% block content %}

    <form class="navbar-form navbar-right" action="." method="get">
        <!-- edit -->
        <a id="edit_entry" href="{% url 'proposal:entry_edit' entry.id %}">
            <button type="button" class="btn btn-success">
                <span class="fa fa-pencil"></span> Editar
            </button>
        </a>
        <!-- <p name="filter_link" class="pull-right"><a href="">Produtos em baixo estoque</a></p> -->
        <!-- add -->
    	<a class="btn btn-primary" href="{% url 'proposal:create_proposal_url' entry.id %}"><i class="fa fa-plus"></i> Criar Orçamento</a>
	</form>

<div>	
	<table class="table table-user-information">
		<tbody>
			<tr>
				<td><h1>{{ object.work }}</h1></td>
			</tr>
			<tr>
				<th class="col-md-3 text-right">Cliente</th>
				<td>{{ object.work.customer }}</td>
			</tr>
			<tr>
				<th class="col-md-3 text-right">Prioridade</th>
				<td>{{ object.get_priority_display }}</td>
			</tr>
			<tr>
				<th class="col-md-3 text-right">Categoria</th>
				<td>{{ object.get_category_display }}</td>
			</tr>
			<tr>
				<th class="col-md-3 text-right">Obra</th>
				<td>{{ object.work }}</td>
			</tr>
			<tr>
				<th class="col-md-3 text-right">Contato</th>
				<td>{{ object.person }}</td>
			</tr>
			{% if object.description %}
				<tr>
					<th class="col-md-3 text-right">Descrição</th>
					<td>{{ object.description }}</td>
				</tr>
			{% endif %}
            <tr>
                <th class="col-md-3 text-right">Vendedor</th>
                <td>{{ object.seller|default:"---" }}</td>
            </tr>

		</tbody>
	</table>
</div>

{% endblock content %}

orcamentos/proposal/templates/proposal/proposal_detail.html
{% extends "base.html" %}
{% load core_status_tags %}

{% block title %}
  <title>Proposal Detail</title>
{% endblock title %}

{% block content %}

  {% for message in messages %}
    {% if 'success' in message.tags %}
    <p class="alert alert-success" role="alert"><span style="font-weight:bold">{{ message }}</span></p>
    {% else %}
    <p class="alert alert-danger" role="alert"><span style="font-weight:bold">{{ message }}</span></p>
    {% endif %}
  {% endfor %}

    <form class="navbar-form navbar-right" action="." method="get">
        <!-- cancel - Button trigger modal -->
        {% if object.status != 'a' %}
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModalCancel">
              <span class="fa fa-close"></span> Cancelar
            </button>
        {% endif %}
        <!-- edit -->
        <a id="edit_proposal" href="{% url 'proposal:proposal_edit' proposal.id %}">
            <button type="button" class="btn btn-success">
                <span class="fa fa-pencil"></span> Editar
            </button>
        </a>
      
      {% if object.status == 'co' %}
        <a class="btn btn-primary" href="{% url 'proposal:create_contract_url' proposal.id %}"><i class="fa fa-plus"></i> Criar Contrato</a>
      {% elif object.status == 'a' %}
        <a class="btn btn-primary" href="{% url 'proposal:contract_detail' contract_id %}"><i class="fa fa-star"></i> Visualizar Contrato</a>
      {% endif %}

    {% if object.status != 'a' %}
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-blue" data-toggle="modal" data-target="#myModal">
      <span class="fa fa-check"></span> Concluir Orçamento
    </button>
    {% endif %}

    <!-- Opção -->
    <a class="btn btn-info" href="#myModalOption" data-toggle="modal"><i class="fa fa-copy"></i> Criar Opções</a>

  </form>

<div>
  <table class="table table-user-information">
    <tbody>
      <tr>
        <td><h1>{{ object.codigo }}</h1></td>

        <td valign="middle" class="text-info"><i class="fa fa-fw fa-3x {% status_icon proposal.status %}"></i> {{ object.get_status_display }}</td>


      </tr>
      <tr>
        <th class="col-md-3 text-right">Criado em</th>
        <td>{{ object.created_orc }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Categoria</th>
        <td>{{ object.get_category_display }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Cliente</th>
        <td><h2><a href="{{ object.get_customer_url }}">{{ object.cliente }}</a></h2></td>
      </tr>
        <th class="col-md-3 text-right">Tipo de cliente</th>
        <td>{{ object.cliente.get_customer_type_display }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Obra</th>
        <td><h2><a href="{{ object.get_work_url }}">{{ object.work }}</a></h2></td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Endereço</th>
        <td>{{ object.get_address|default:"---" }} </td>
      </tr>
      {% if object.person %}
        <tr>
          <th class="col-md-3 text-right">Contato</th>
          <td><a href="{{ object.get_person_url }}">{{ object.person }}</a></td>
        </tr>
        <tr>
          <th class="col-md-3 text-right"><span class="glyphicon glyphicon-envelope"></span></th>
          <td><a href="mailto:{{ object.person.email }}">{{ object.person.email }}</a></td>
        </tr>
        <tr>
          <th class="col-md-3 text-right"><span class="glyphicon glyphicon-phone-alt"></span></th>
          <td>{{ object.person.phone1 }}</td>
        </tr>
      {% endif %}

      <tr>
        <th class="col-md-3 text-right">Descrição</th>
        <td>{{ object.description|default:"---" }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Funcionário</th>
        <td>{{ object.get_employee|default:"---" }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Vendedor</th>
        <td>{{ object.get_seller|default:"---" }}</td>
      </tr>
      {% if object.price != 0 %}
        <tr>
          <th class="col-md-3 text-right">Valor</th>
          <td>{{ object.get_price }}</td>
        </tr>
      {% endif %}
      {% if object.date_conclusion %}
        <tr>
          <th class="col-md-3 text-right">Conclusão</th>
          <td>{{ object.date_conclusion }}</td>
        </tr>
      {% endif %}
      {% if object.obs %}
        <tr>
          <th class="col-md-3 text-right">Observação</th>
          <td>{{ object.obs }}</td>
        </tr>
      {% endif %}

    </tbody>
  </table>
</div>


<!-- Modal -->
<div class="modal fade" id="myModalCancel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Cancelar Orçamento</h4>
      </div>
    <form action="{% url 'proposal:cancel_proposal' proposal.id %}" method="POST">
      <div class="modal-body">
        {% csrf_token %}  
        <h5>Deseja cancelar o orçamento?</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button id="id_submit" type="submit" class="btn btn-danger">Cancelar</button>
      </div>
    </form>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Concluir Orçamento</h4>
      </div>
    <form action="{% url 'proposal:conclude_proposal' proposal.id %}" method="POST">
      <div class="modal-body">
      {% csrf_token %}  
          <input id="id_price" name="price" class="form-control" type="number" step="0.01" placeholder="Digite o valor" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button id="id_submit" type="submit" class="btn btn-primary">Atualizar</button>
        <!-- <input id="id_submit" type="submit" class="btn btn-primary" value="Atualizar" data-dismiss="modal" /> -->
      </div>
    </form>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModalOption" tabindex="-1" role="dialog" aria-labelledby="myModalLabelOption">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabelOption">Criar Opções</h4>
      </div>
    <form action="{% url 'proposal:create_option_url' proposal.id %}" method="POST">
      <div class="modal-body">
        {% csrf_token %}
        <h5>Digite quantas opções você quer criar.</h5>
        <input id="id_option_prop" name="option_prop" class="form-control" type="number" min="1" step="1" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button id="id_submit4" type="submit" class="btn btn-primary">OK</button>
      </div>
    </form>
    </div>
  </div>
</div>

<script>

    //close alert after 3 seconds
    window.setTimeout(function() {
      $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove();
      });
    }, 3000);

  $(function(){
    $('#myModal').on('shown.bs.modal', function(){
      let price = "{{ object.price }}".replace(',', '.');
      $('#id_price').val(price);
      $('#id_price').focus();
    });
    $("#id_submit").click(function(){
        var v = $('#id_price').val();
        console.log(v);
        if (v <= 0) {
          console.log("O valor deve ser positivo.");
        };
    });
  });

  $(function(){
    $('#myModalCancel').on('shown.bs.modal', function(){});
    $("#id_submit").click(function(){});
  });
</script>

{% endblock content %}